### ISSUE TITLE
Errors in Configurable API gateway tutorial

### ISSUE THREAD

**Issue by Mateusz512** [Knotx/knotx-website#59]
1.  `api-gateway.yml` is incorrect, since it is referring to the actual structure of https://github.com/Knotx/knotx-example-project repository and not the structure created by following the tutorial:
`../common-services/` should be replaced with `./services` since the tutorial is telling to create directory `services` under the root of the project
Do we want to change the name of the directory or update `api-gateway.yml` ?
2. It would be nice to have one additional info to run `docker swarm init` before trying to deploy the stack ;)

**Comment by tomaszmichalak** [comment]
Hi @Mateusz512,
1. `../common-services/` are used in API Gateway and Template Processing tutorials, you can see `gateway-api.yml` and `template-processing.yml`. The @marcinkp intention was to not duplicate those services data. Can we instead update tutorial and mention that we made such improvement? 
2. Please add.

Can you please fix those issues?

**Comment by Mateusz512** [comment]
On it!
